name:                servant-gp
version:             0.1.0.0
github:              "githubuser/servant-gp"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-gp#readme>
language:            GHC2021

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- servant-server
- servant
- servant-docs
- servant-swagger
- servant-swagger-ui
- servant-swagger-ui-core
- swagger2
- servant-exceptions
- string-conversions
- libiserv
- base-compat-batteries
- time
- wai
- warp
- bytestring
- http-types
- text
- lens
- transformers
- directory
- mtl
- process
- exceptions
- http-media
- generic-persistence
- HDBC-sqlite3
- HDBC
- monad-control
- resource-pool

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  servant-gp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-gp

tests:
  servant-gp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-gp
    - hspec
    - hspec-wai
